services:
  discord-rss-bot:
    # Use pre-built image from Docker Hub
    image: isyuricunha/discord-rss-bot:latest
    container_name: discord-rss-bot
    restart: unless-stopped
    environment:
      # Required: Discord webhook URL
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      
      # Optional: Bot behavior settings
      - CHECK_INTERVAL=${CHECK_INTERVAL:-300}
      - POST_DELAY=${POST_DELAY:-3}
      - COOLDOWN_DELAY=${COOLDOWN_DELAY:-60}
      - MAX_POST_LENGTH=${MAX_POST_LENGTH:-1900}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-800}
      - FEED_TIMEOUT=${FEED_TIMEOUT:-30}
      
      # Optional: Custom RSS feeds (from .env file)
      # Option 1: Universal feeds (simple, all feeds in one variable)
      # RSS_FEEDS=https://example.com/rss,https://another.com/feed,https://third.com/rss
      
      # Option 2: Category-based feeds (organized by categories with emojis)
      # RSS_FEEDS_NEWS=https://g1.globo.com/dynamo/rss2.xml,https://rss.uol.com.br/feed/noticias.xml
      # RSS_FEEDS_TECHNOLOGY=https://canaltech.com.br/rss/,https://tecnoblog.net/feed/
      # RSS_FEEDS_SPORTS=https://globoesporte.globo.com/rss/ultimas/
      # RSS_FEEDS_BUSINESS=https://www.infomoney.com.br/rss/
      
      # Note: RSS_FEEDS takes priority over category-based feeds
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - rss-bot-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; conn = sqlite3.connect('/app/data/posted_hashes.db'); conn.close()"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 30s

networks:
  rss-bot-network:
    driver: bridge
